# Generated by Django 5.0.3 on 2024-03-30 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Admins", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SN", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "student_name",
                    models.CharField(
                        blank=True, default="No name", max_length=100, null=True
                    ),
                ),
                ("Sex", models.CharField(blank=True, max_length=100, null=True)),
                ("student_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "student_pin",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "student_Photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="assets/Students"
                    ),
                ),
                (
                    "student_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Admins.class"
                    ),
                ),
            ],
        ),
    ]
