# Generated by Django 5.0.3 on 2024-03-30 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admins", "0002_administrator"),
        ("Students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="student_school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Admins.school",
            ),
        ),
    ]
