# Generated by Django 5.0.3 on 2024-04-10 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admins", "0012_academicsession_enddate_academicsession_startdate"),
        ("Students", "0003_remove_student_sn_student_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_school",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Admins.school",
            ),
            preserve_default=False,
        ),
    ]
