# Generated by Django 5.0.3 on 2024-04-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Students", "0004_alter_student_student_school"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="student_name",
            new_name="firstname",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="Sex",
            new_name="sex",
        ),
        migrations.AddField(
            model_name="student",
            name="othername",
            field=models.CharField(
                blank=True, default="No name", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="surname",
            field=models.CharField(
                blank=True, default="No name", max_length=100, null=True
            ),
        ),
    ]
