# Generated by Django 5.0.3 on 2024-04-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0006_alter_student_firstname_alter_student_othername_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_Photo',
            new_name='headshot',
        ),
    ]
