# Generated by Django 5.0.3 on 2024-04-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0007_rename_student_photo_student_headshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(blank=True, default='Student', max_length=100),
        ),
    ]
