# Generated by Django 3.2.7 on 2024-11-30 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0024_alter_notification_options'),
        ('Students', '0008_student_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admins.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.student')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admins.class')),
            ],
        ),
    ]
