# Generated by Django 3.2.7 on 2024-11-30 10:41

from django.db import migrations

def migrate_student_classes(apps, schema_editor):
    # Get models
    Students = apps.get_model('Students', 'Student')
    StudentClassEnrollment = apps.get_model('Students', 'StudentClassEnrollment')
    AcademicSession = apps.get_model('Admins', 'AcademicSession')
    Class = apps.get_model('Admins', 'Class')

    # Create a default session if none exist , for the Previous Session
    session, _ = AcademicSession.objects.get_or_create(session="2023/2024")

    # Iterate through all students and migrate their class data
    for student in Students.objects.all():
        if student.student_class:
            StudentClassEnrollment.objects.create(
                student=student,
                student_class=student.student_class,
                academic_session=session,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0009_studentclassenrollment'),
    ]

    operations = [
        migrations.RunPython(migrate_student_classes)
    ]
