# Generated by Django 3.2.7 on 2024-11-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0010_auto_20241130_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
    ]
