
# # Results endpoints
#     path('getResults/', getResults, name='getResults'),
#     path('updateResult/<int:result_id>', updateResult, name='updateResult'),
#     path('postResults/', postResults, name='postResults'),

#     path('getResultSummaries/', getResultSummaries, name='getResultSummaries'),
#     path('postResultSummaries/', postResultSummaries, name='postResultSummaries'),

#     path('getAnnualResults/', getAnnualResults, name='getAnnualResults'),
#     path('updateAnnualResult/<int:result_id>', updateAnnualResult, name='updateAnnualResult'),
#     path('postAnnualResults/', postAnnualResults, name='postAnnualResults'),

#     path('getAnnualResultSummaries/', getAnnualResultSummaries, name='getAnnualResultSummaries'),
#     path('postAnnualResultSummaries/', postAnnualResultSummaries, name='postAnnualResultSummaries'),


# get student results for a Particular subject , class, term and session
###
POST http://127.0.0.1:8000/resultapi/getResults/
Content-Type: application/json

{
    "term_id": "3",
    "session_id": "3",
    "school_id": "2",
    "class_id": "2",
    "subject_id": "2"
  }

###
# update a student subject result entry
PUT http://127.0.0.1:8000/resultapi/updateResult/10/
Content-Type: application/json


{
    "FirstTest": "4",
    "FirstAss": "5",
    "MidTermTest": "6",
    "Project": "9",
    "SecondAss": "3",
    "SecondTest": "5",
    "Exam": "30",
    "is_offering": true
}




###
PUT http://127.0.0.1:8000/resultapi/postResults/
Content-Type: application/json


[
  {
    "id": 5,
    "firstname": "Ndukwe",
    "surname": "Kosisochukwu",
    "middlename": "Ifeanyi",
    "studentID": "smss/2225",
    "subject": "English",
    "is_offering": true,
    "FirstTest": "4",
    "FirstAss": "2",
    "MidTermTest": "6",
    "Project": "9",
    "SecondAss": "2",
    "SecondTest": "3",
    "Exam": "30",
    "Total": "65",
    "Grade": "A",
    "SubjectPosition": "6th",
    "Remark": "Excellent",
    "published": false
  },
  {
    "id": 6,
    "firstname": "Afunwa",
    "surname": "Chimdindu",
    "middlename": "Precious",
    "studentID": "smss/6759",
    "subject": "English",
    "is_offering": true,
    "FirstTest": "4",
    "FirstAss": "5",
    "MidTermTest": "6",
    "Project": "9",
    "SecondAss": "3",
    "SecondTest": "5",
    "Exam": "30",
    "Total": "68",
    "Grade": "A",
    "SubjectPosition": "2nd",
    "Remark": "Excellent",
    "published": false
  }
]


# For the Result Summaries
###
POST http://127.0.0.1:8000/resultapi/getResultSummaries/
Content-Type: application/json

{
    "term_id": "5",
    "session_id": "2",
    "school_id": "2",
    "class_id": "2"
  }

###
POST http://127.0.0.1:8000/resultapi/postResultSummaries/
Content-Type: application/json

[
  {
    "id": 1,
    "firstname": "Ndukwe",
    "surname": "Kosisochukwu",
    "middlename": "Ifeanyi",
    "TotalScore": "789",
    "Totalnumber": 2,
    "Average": "65",
    "Position": "6th",
    "Remark": "Excellent",
    "subjects_total": [
      {
        "subject_code": "Maths",
        "subject_total": "-"
      },
      {
        "subject_code": "Eng",
        "subject_total": "65"
      }
    ]
  },
  {
    "id": 2,
    "firstname": "Afunwa",
    "surname": "Chimdindu",
    "middlename": "Precious",
    "TotalScore": "657",
    "Totalnumber": 2,
    "Average": "68",
    "Position": "2nd",
    "Remark": "Excellent",
    "subjects_total": [
      {
        "subject_code": "Maths",
        "subject_total": "-"
      },
      {
        "subject_code": "Eng",
        "subject_total": "68"
      }
    ]
  }
]




# For the Annual Subject Results

###
POST http://127.0.0.1:8000/resultapi/getAnnualResults/
Content-Type: application/json

{
    "session_id": "3",
    "school_id": "2",
    "class_id": "2",
    "subject_id": "2"
  }


###
PUT http://127.0.0.1:8000/resultapi/updateAnnualResult/1/
Content-Type: application/json


{
    "FirstTermTotal": "65",
    "SecondTermTotal": "65",
    "ThirdTermTotal": "-",
    "is_offering": true
}

###
POST http://127.0.0.1:8000/resultapi/postAnnualResults/
Content-Type: application/json

[
  {
    "id": 1,
    "firstname": "Ndukwe",
    "surname": "Kosisochukwu",
    "middlename": "Ifeanyi",
    "studentID": "smss/2225",
    "FirstTermTotal": "65",
    "SecondTermTotal": "65",
    "ThirdTermTotal": "-",
    "Total": "124",
    "Average": "65",
    "Grade": "B",
    "SubjectPosition": "6th",
    "Remark": "Good",
    "is_offering": true
  },
  {
    "id": 2,
    "firstname": "Afunwa",
    "surname": "Chimdindu",
    "middlename": "Precious",
    "studentID": "smss/6759",
    "FirstTermTotal": "68",
    "SecondTermTotal": "68",
    "ThirdTermTotal": "-",
    "Total": "136",
    "Average": "68",
    "Grade": "A",
    "SubjectPosition": "2nd",
    "Remark": "Excellent",
    "is_offering": true
  }
]


# Annual Result Summaries
###
POST http://127.0.0.1:8000/resultapi/getAnnualResultSummaries/
Content-Type: application/json

{
    "session_id": "3",
    "school_id": "2",
    "class_id": "2"
  }


###
POST http://127.0.0.1:8000/resultapi/postAnnualResultSummaries/
Content-Type: application/json


[
  {
    "id": 1,
    "firstname": "Ndukwe",
    "surname": "Kosisochukwu",
    "middlename": "Ifeanyi",
    "subjects": [
      {
        "Maths": {
          "1st": "-",
          "2nd": "-",
          "3rd": "-",
          "Total": "-",
          "Ave": "-"
        }
      },
      {
        "Eng": {
          "1st": "65",
          "2nd": "65",
          "3rd": "-",
          "Total": "124",
          "Ave": "65"
        }
      }
    ],
    "TotalScore": "1234",
    "Totalnumber": 2,
    "Average": "65",
    "Position": "6th",
    "PrincipalVerdict": "Promoted to the next class"
  },
  {
    "id": 2,
    "firstname": "Afunwa",
    "surname": "Chimdindu",
    "middlename": "Precious",
    "subjects": [
      {
        "Maths": {
          "1st": "-",
          "2nd": "-",
          "3rd": "-",
          "Total": "-",
          "Ave": "-"
        }
      },
      {
        "Eng": {
          "1st": "68",
          "2nd": "68",
          "3rd": "-",
          "Total": "136",
          "Ave": "68"
        }
      }
    ],
    "TotalScore": "678",
    "Totalnumber": 2,
    "Average": "34",
    "Position": "32nd",
    "PrincipalVerdict": "Not promoted to the next class"
  }
]

###
# get student results for a Particular subject , class, term and session

# '/getresultsummary/',
        # '/getsubjectresult/',
        # '/getsubjectresults/',
        # '/getannualresultsummary/',
        # '/getannualsubjectresult/',
        # '/getannualsubjectresults/',

