

# ///////////////////////////////////////////////////////////////////////////////
#  student endpoints
#         "studentsapi/", # get all students
#         "<int:school_id>"
#         "<int:school_id>/<int:class_id>/", # get students based on the School ID and Class ID
#         "student/<int:student_id>/", # get a student based on his/her Student ID
#         "create/<int:school_id>/<int:class_id>/", # create a student based on the School ID and Class ID
#         "update/<int:student_id>/", # update a student based on his/her Student ID
#         "delete/<int:student_id>/",

# get all entries for a School
GET http://127.0.0.1:8000/studentsapi/2/

###
# get all entries for a Particular class in a School
GET http://127.0.0.1:8000/studentsapi/2/3/


# get single entry
###
GET http://127.0.0.1:8000/studentsapi/student/10


# create an entry
###
POST http://127.0.0.1:8000/studentsapi/create/2/3/
Content-Type: application/json

{
    "firstname": "Chidimma",
    "surname": "Ekwunife",
    "othername": "",
    "sex": "Female"
  }

###
# update an entry
PUT http://127.0.0.1:8000/studentsapi/update/1/
Content-Type: application/json


{
    "othername": "Ifeanyi",
    "sex": "Male"
  }

###
# delete an entry
DELETE http://127.0.0.1:8000/studentsapi/delete/6/





/////////////////////////////////////////////////////////////////////////////////
# # Teachers endpoints
#          "<int:school_id>/",  # get all teachers based on the School ID and Class ID
#         "teacher/<int:teacher_id>/",  # get a teacher based on his/her Teacher ID
#         "create/<int:school_id>/",  # create a teacher based on the School ID and Class ID
#         "<int:teacher_id>/update/",  # update a teacher based on his/her Teacher ID
#         "<int:teacher_id>/delete/",  # delete a teacher based on his/her Teacher ID
# get all entries
###
GET http://127.0.0.1:8000/teachersapi/2/


# get single entry
###
GET http://127.0.0.1:8000/teachersapi/teacher/5/


# create an entry
###
POST http://127.0.0.1:8000/teachersapi/create/2/
Content-Type: application/json

{
  "id": 8,
  "user": "@OkparaMary6057",
  "classes_taught": [],
  "subjects_taught": [],
  "school": {
    "id": 2,
    "name": "Kings College"
  },
  "classFormed": null,
  "firstName": "Okpara",
  "lastName": "Mary",
  "phone_number": "",
  "email": "",
  "teachers_id": "teacher/6057",
  "role": "",
  "is_formteacher": false,
  "headshot": null
}


###
# update an entry
PUT http://127.0.0.1:8000/teachersapi/update/2/
Content-Type: application/json


{

}

###
# delete an entry
DELETE http://127.0.0.1:8000/teachersapi/delete/10/