


# admins api endpoints
# 

#        "academicsessions/",  # get all academic sessions in a school based on its ID
#        "academicsessions/create/",  # create an academic session in a school based on its ID
#        "academicsessions/<int:session_id>/",  # get an academic session based on its ID
#        "academicsessions/<int:session_id>/update/",  # update an academic session based on its ID
#        "academicsessions/<int:session_id>/delete/",  # delete an academic session based on its ID

#        "terms/",  # get all terms in an academic session based on its ID
#        "terms/create/",  # create a term in an academic session based on its ID
#        "terms/<int:term_id>/",  # get a term based on its ID
#        "terms/<int:term_id>/update/",  # update a term based on its ID
#        "terms/<int:term_id>/delete/",  # delete a term based on its ID  

#          path('classes/', getClasses, name='classes'),
        #path('classes/create/', createClass, name='create_class'),
        #path('classes/<int:class_id>/', getClass, name='class'),
        #path('classes/<int:class_id>/update/', updateClass, name='update_class'),
        #path('classes/<int:class_id>/delete/', deleteClass, name='delete_class'), 

    #     path('subjects/', getSubjects, name='subjects'),
    #     path('subjects/create/', createSubject, name='create_subject'),
    #     path('subjects/<int:subject_id>/', getSubject, name='subject'),
    #     path('subjects/<int:subject_id>/update/', updateSubject, name='update_subject'),
    #     path('subjects/<int:subject_id>/delete/', deleteSubject, name='delete_subject'), 

    #     path('schools/', getSchools, name='schools'),
    #     path('schools/create/', createSchool, name='create_school'),
    #     path('schools/<int:school_id>/', getSchool, name='school'),
    #     path('schools/<int:school_id>/update/', updateSchool, name='update_school'),
    #     path('schools/<int:school_id>/delete/', deleteSchool, name='delete_school'),

    #     path('admins/<int:school_id>/', getAdmins, name='admins'),
    #     path('admins/<int:school_id>/create/', createAdmin, name='create_admin'),
    #     path('admins/<int:school_id>/<int:admin_id>/', getAdmin, name='admin'),
    #     path('admins/<int:admin_id>/update/', updateAdmin, name='update_admin'),
    #     path('admins/<int:admin_id>/delete/', deleteAdmin, name='delete_admin'),
    
#      path('subjectallocations/<int:school_id>', getSubjectAllocations, name='subject_allocations'),
    # path('subjectallocations/<int:school_id>/create/', createSubjectAllocation, name='create_subject_allocation'),
    # path('subjectallocations/<int:school_id>/<int:subjectallocation_id>/', getSubjectAllocation, name='subject_allocation'),
    # path('subjectallocations/<int:subjectallocation_id>/update/', updateSubjectAllocation, name='update_subject_allocation'),
    # path('subjectallocations/<int:subjectallocation_id>/delete/', deleteSubjectAllocation, name='delete_subject_allocation'),


#  student endpoints
#          "<int:school_id>/<int:class_id>/", # get students based on the School ID and Class ID
#         "create/<int:school_id>/<int:class_id>/", # create a student based on the School ID and Class ID
#         "<int:student_id>/", # get a student based on his/her Student ID
#         "<int:student_id>/update/", # update a student based on his/her Student ID
#         "<int:student_id>/delete/",

GET http://127.0.0.1:8000/studentsapi/2/2/


###

POST http://127.0.0.1:8000/studentsapi/create/2/2/
Content-Type: application/json

{
    "student_name": "Ndukwe jannetse",
    "Sex": "Female",
    "student_Photo": null
}

###
GET http://127.0.0.1:8000/studentsapi/3/


###

PUT http://127.0.0.1:8000/studentsapi/2/update/
Content-Type: application/json


{
    "student_name": "Ndukwe kosiso",
    "Sex": "Female",
    "student_Photo": null,
    "schoolid": 3,
    "classid": 2
}

###

DELETE http://127.0.0.1:8000/studentsapi/4/delete/