# Generated by Django 5.0.3 on 2024-03-30 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Class", models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Schoolid", models.IntegerField()),
                (
                    "Schoollogo",
                    models.ImageField(blank=True, upload_to="assets/Schoollogo"),
                ),
                ("Schoolname", models.CharField(blank=True, max_length=300)),
                ("SchoolPhonenumber", models.CharField(blank=True, max_length=300)),
                ("Schoolmotto", models.CharField(blank=True, max_length=300)),
                ("Schoollocation", models.CharField(blank=True, max_length=300)),
                ("Facebookpage", models.CharField(blank=True, max_length=300)),
                ("Twitterpage", models.CharField(blank=True, max_length=300)),
                ("Whatsapp", models.CharField(blank=True, max_length=300)),
                ("Emailaddress", models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_code", models.CharField(max_length=100)),
                ("subject_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Subjectallocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classname",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Admins.class",
                    ),
                ),
                ("subjects", models.ManyToManyField(to="Admins.subject")),
            ],
        ),
    ]
