# Generated by Django 5.0.3 on 2024-03-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admins", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Administrator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adminid", models.IntegerField()),
                ("adminfirstname", models.CharField(blank=True, max_length=100)),
                ("adminlastname", models.CharField(blank=True, max_length=100)),
                ("admin_id", models.CharField(blank=True, max_length=100)),
                ("adminphonenumber", models.CharField(blank=True, max_length=100)),
                ("adminemail", models.EmailField(blank=True, max_length=100)),
                (
                    "adminphoto",
                    models.ImageField(blank=True, upload_to="assets/administrator"),
                ),
                ("adminrole", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
