# Generated by Django 5.0.3 on 2024-03-30 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admins", "0003_term_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="administrator",
            name="adminid",
        ),
        migrations.AddField(
            model_name="academicsession",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Admins.school",
            ),
        ),
        migrations.AddField(
            model_name="administrator",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Admins.school",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Admins.school",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Admins.school",
            ),
        ),
        migrations.AddField(
            model_name="subjectallocation",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Admins.school",
            ),
        ),
    ]
