# Generated by Django 5.0.3 on 2024-03-30 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Admins", "0004_remove_administrator_adminid_academicsession_school_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="school",
            old_name="SchoolPhonenumber",
            new_name="Schoolofficialline",
        ),
    ]
