# Generated by Django 5.0.3 on 2024-04-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admins", "0005_rename_schoolphonenumber_school_schoolofficialline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academicsession",
            name="school",
        ),
        migrations.RemoveField(
            model_name="class",
            name="school",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="school",
        ),
        migrations.RemoveField(
            model_name="term",
            name="session",
        ),
        migrations.AddField(
            model_name="academicsession",
            name="terms",
            field=models.ManyToManyField(blank=True, to="Admins.term"),
        ),
        migrations.AddField(
            model_name="school",
            name="Subjects",
            field=models.ManyToManyField(blank=True, to="Admins.subject"),
        ),
        migrations.AddField(
            model_name="school",
            name="classes",
            field=models.ManyToManyField(blank=True, to="Admins.class"),
        ),
        migrations.AddField(
            model_name="school",
            name="session",
            field=models.ManyToManyField(blank=True, to="Admins.academicsession"),
        ),
    ]
