# Generated by Django 5.0.3 on 2024-04-01 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Admins", "0006_remove_academicsession_school_remove_class_school_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="school",
            old_name="Twitterpage",
            new_name="Twitterhandle",
        ),
        migrations.RenameField(
            model_name="school",
            old_name="Whatsapp",
            new_name="Whatsapplink",
        ),
    ]
