# Generated by Django 5.0.3 on 2024-04-01 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Admins", "0007_rename_twitterpage_school_twitterhandle_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="school",
            name="Schoolid",
        ),
    ]
