# Generated by Django 5.0.3 on 2024-04-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admins", "0009_alter_school_schoollogo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrator",
            name="adminrole",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Manager", "Manager"),
                    ("Principal", "Principal"),
                    ("ICT manager", "ICT manager"),
                    ("Site manager", "site manager"),
                ],
                max_length=100,
            ),
        ),
    ]
