# Generated by Django 5.0.3 on 2024-04-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admins", "0010_alter_administrator_adminrole"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrator",
            name="adminphoto",
            field=models.ImageField(
                blank=True, null=True, upload_to="assets/administrator"
            ),
        ),
        migrations.AlterField(
            model_name="administrator",
            name="adminrole",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Manager", "Manager"),
                    ("Principal", "Principal"),
                    ("ICT manager", "ICT manager"),
                    ("Site Admin", "site Admin"),
                ],
                max_length=100,
            ),
        ),
    ]
