# Generated by Django 5.0.3 on 2024-04-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admins", "0011_alter_administrator_adminphoto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicsession",
            name="enddate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="academicsession",
            name="startdate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
