# Generated by Django 5.0.3 on 2024-04-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0012_academicsession_enddate_academicsession_startdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrator',
            old_name='adminfirstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='administrator',
            old_name='adminphoto',
            new_name='headshot',
        ),
        migrations.RenameField(
            model_name='administrator',
            old_name='adminlastname',
            new_name='sex',
        ),
        migrations.AddField(
            model_name='administrator',
            name='surname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
