# Generated by Django 3.2.7 on 2024-04-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0014_rename_adminrole_administrator_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='Class',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
