# Generated by Django 3.2.7 on 2024-04-30 03:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0015_alter_class_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Newsletterfile', models.FileField(blank=True, null=True, upload_to='assets/newsletter')),
                ('Newsletter', ckeditor.fields.RichTextField(default='None', null=True)),
                ('Newsletterdate', models.DateField(auto_now_add=True, null=True)),
                ('Newslettersession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admins.academicsession')),
                ('Newsletterterm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admins.term')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admins.school')),
            ],
        ),
    ]
