# Generated by Django 3.2.7 on 2024-05-06 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0016_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Instagramlink',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='school',
            name='Schooltype',
            field=models.CharField(blank=True, choices=[('Creche', 'Creche'), ('Nursery', 'Nursery'), ('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Primary and Secondary', 'Primary and Secondary'), ('Tertiary', 'Tertiary')], max_length=100),
        ),
        migrations.CreateModel(
            name='Notfication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=100)),
                ('Notification', models.TextField(blank=True)),
                ('Notificationdate', models.DateField(auto_now_add=True, null=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admins.school')),
            ],
        ),
    ]
