# Generated by Django 3.2.7 on 2024-05-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0017_auto_20240506_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='notfication',
            name='Notification_group',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
