# Generated by Django 3.2.7 on 2024-05-06 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0018_notfication_notification_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notification_group', models.CharField(blank=True, choices=[('Teachers', 'Teachers'), ('Students', 'Students'), ('Admins', 'Admins'), ('Bursar', 'Bursar'), ('All', 'All')], max_length=100)),
                ('headline', models.CharField(blank=True, max_length=100)),
                ('Notification', models.TextField(blank=True)),
                ('Notificationdate', models.DateField(auto_now_add=True, null=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admins.school')),
            ],
        ),
        migrations.DeleteModel(
            name='Notfication',
        ),
    ]
