# Generated by Django 3.2.7 on 2024-05-06 22:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Admins', '0019_auto_20240506_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_seen',
        ),
        migrations.AddField(
            model_name='notification',
            name='users_seen',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
