# Generated by Django 3.2.7 on 2024-05-06 23:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Admins', '0020_auto_20240506_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='users_seen',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
