# Generated by Django 3.2.7 on 2024-05-07 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0021_alter_notification_users_seen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-Notificationdate']},
        ),
    ]
