# Generated by Django 3.2.7 on 2024-05-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admins', '0023_alter_notification_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
    ]
