# Generated by Django 5.0.3 on 2024-03-30 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admins", "0002_administrator"),
        ("Teachers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="Email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="teacher",
            old_name="FirstName",
            new_name="firstName",
        ),
        migrations.RenameField(
            model_name="teacher",
            old_name="Headshot",
            new_name="headshot",
        ),
        migrations.RenameField(
            model_name="teacher",
            old_name="LastName",
            new_name="lastName",
        ),
        migrations.RenameField(
            model_name="teacher",
            old_name="Phone_number",
            new_name="phone_number",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="Role",
        ),
        migrations.AddField(
            model_name="teacher",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Admins.school",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("Teacher", "Teacher"), ("Formteacher", "Formteacher")],
                default="Teacher",
                max_length=200,
            ),
        ),
    ]
