# Generated by Django 5.0.3 on 2024-04-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Teachers", "0002_rename_email_teacher_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="is_formteacher",
            field=models.BooleanField(default=False),
        ),
    ]
