# Generated by Django 5.0.3 on 2024-04-09 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admins", "0012_academicsession_enddate_academicsession_startdate"),
        ("Teachers", "0003_teacher_is_formteacher"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="classes_taught",
            field=models.ManyToManyField(
                blank=True, related_name="assigned_classes", to="Admins.class"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="subjects_taught",
            field=models.ManyToManyField(blank=True, to="Admins.subject"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                blank=True,
                default=2,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
