# Generated by Django 5.0.3 on 2024-04-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0005_alter_teacher_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='lastName',
            new_name='surname',
        ),
        migrations.AddField(
            model_name='teacher',
            name='sex',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
