# Generated by Django 5.0.3 on 2024-04-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Teachers", "0006_rename_lastname_teacher_surname_teacher_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="address",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
